version: "3"
services:
  mysql:
    container_name: user-mysql
    image: 'mysql:8.0.36'
    environment:
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/init/:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    networks:
      - user-network

  user-api:
    container_name: user-api
    build: .
    env_file:
      - env/.env
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    networks:
      - user-network

networks:
  user-network: