version: '3.8'

services:
  allclimb-black:
    image: ghcr.io/allclimb/allclimb-black:${TAG}  # 'TAG'는 GitHub Actions에서 설정
    container_name: allclimb-black
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}  # 'ENV'는 dev 또는 prod로 설정
    networks:
      - allclimb-network

networks:
  allclimb-network:
    driver: bridge
