spring:
  pid:
    file: allclimb-black.pid
  profiles:
    active: dev
    include:
      - database

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  redirect: ${REGISTER_TOKEN_REDIRECT_URI}
  access-token:
    expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token:
    expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

server:
  port: 8080
  servlet:
    context-path: /all-climb/api

springdoc:
  swagger-ui:
    disable-swagger-default-url: true   #디폴트 페이지 안나오게
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always