spring:
  pid:
    file: allclimb-black.pid
  profiles:
    active: ${SPRING_PROFILE:local}   # 기본 프로파일은 'local'
    include:
      - database

server:
  port: 8080
  servlet:
    context-path: /all-climb/api

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html  # 이 경로를 context-path와 일치하도록 설정
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서는 이 경로에서 제공

  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always