#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/all-climb

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/film_db
    username: film_api
    password: film_api1234
  jpa:
    show-sql: true