name: Java CI with Gradle and GHCR

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  MODULE: "user-api"  # 서브모듈 이름을 환경 변수로 지정하여 쉽게 변경 가능

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          gradle-version: '8.7'

      # 지정된 서브모듈을 빌드
      - name: Build with Gradle Wrapper
        run: ./gradlew :${{ env.MODULE }}:build -x test

      # Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-java-service:${{ env.MODULE }}-latest -f ${{ env.MODULE }}/Dockerfile .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}/my-java-service:${{ env.MODULE }}-latest
